[jira]
user = "user@domain.com"
url = "https://account.atlassian.net"
project = "TEST"
personal-access-token = "zxcv_JIRA_TOKEN"
cache-dir = ".jira_cache"
drafts-dir = "drafts"
plugins-dir = "plugins"
type_id_cutoff = "10100"

