[jira]
user = "user@domain.com"
url = "https://account.atlassian.net"
project = "TEST"
personal-access-token = "zxcv_JIRA_TOKEN"
cache-dir = ".jira_cache"
drafts-dir = "drafts"
plugins-dir = "plugins"
type_id_cutoff = "10100"

[openai]
chat-gpt-activated = true
chat-gpt-base-url = "https://api.openai.com/v1"
chat-gpt-api-key = "socks_off_full_throttle_$%^"
