name: Auto Merge Version Bump PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: |
      startsWith(github.event.pull_request.title, 'Bump version to v') &&
      (
        github.actor == 'github-actions[bot]' ||
        github.actor == github.repository_owner
      )
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (
              pr.user.login === 'github-actions[bot]' &&
              pr.title.startsWith('Bump version to v')
            ) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              console.log(`✅ Auto-merged PR #${pr.number}`);
            } else {
            if (
              console.log(`pr.user.login: #${pr.user.login} #${pr.user.login === 'github-actions[bot]' ? '✅' : '❌'}`);
              console.log(`pr.title: #${pr.title} #${pr.title.startsWith('Bump version to v') ? '✅' : '❌'}`);
              console.log(`ℹ️ Skipping auto-merge for PR #${pr.number}`);
            }
