# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        python-version: 3.12.3
        enable-cache: true
        ignore-nothing-to-cache: true
    - name: Run ruff
      run: uv run ruff check .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude .venv
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude .venv
    - name: Test with pytest and coverage with pytest-cov
      run: |
        uv run pytest --cov
    - name: Pytest coverage html report
      run: |
        uv run pytest --cov-report html --cov
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov
    - name: MyPy
      run: |
        uv run mypy --disallow-untyped-calls --disallow-untyped-defs --disallow-incomplete-defs src
    - name: Install coveralls-python
      run: uv run pip install coveralls
    - name: Run coveralls
      run: coveralls --service=github-actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  auto-merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Decide if auto-merge should run
        id: check-pr-type
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_USER="${{ github.event.pull_request.user.login }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          OWNER="${{ github.repository_owner }}"
          ACTOR="${{ github.actor }}"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

          is_title_ok=false
          is_user_ok=false
          if [[ "$PR_TITLE" == Bump\ version\ to\ v* ]]; then
            is_title_ok=true
            reason_title="pr.title: $PR_TITLE ✅"
          else
            reason_title="pr.title: $PR_TITLE ❌"
          fi
          if [[ "$PR_USER" == "github-actions[bot]" || "$PR_USER" == "$OWNER" ]]; then
            is_user_ok=true
            reason_user="pr.user.login: $PR_USER ✅"
          else
            reason_user="pr.user.login: $PR_USER ❌"
          fi

          if $is_title_ok && $is_user_ok; then
            echo "allowed=true" >> $GITHUB_OUTPUT
            echo "reason=All checks passed: ${reason_title}; ${reason_user}" >> $GITHUB_OUTPUT
            echo "✅ Auto-merge allowed for PR #$PR_NUMBER" >&2
          else
            echo "allowed=false" >> $GITHUB_OUTPUT
            echo "reason=${reason_user}; ${reason_title}" >> $GITHUB_OUTPUT
            echo "ℹ️ Skipping auto-merge for PR #$PR_NUMBER" >&2
            exit 0
          fi
      - name: Validate PR is a clean version bump
        id: validate_bump
        if: steps.check-pr-type.outputs.allowed == 'true'
        run: |
          set -e
          PR_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current PR branch: $PR_BRANCH"
          # Get bump type from PR labels
          BUMP_TYPE=$(gh pr view "$PR_NUMBER" --json labels --jq '.labels[] | select(.name | startswith("bump:")) | .name' | sed 's/bump://')
          if [ -z "$BUMP_TYPE" ]; then
            echo "❌ No bump type label found (bump:patch, bump:minor, bump:major)"
            echo "bump_check=false" >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "Detected bump type: $BUMP_TYPE"
          git fetch origin master
          git checkout origin/master -b _tmp_master
          uv version --bump "$BUMP_TYPE"
          git add pyproject.toml uv.lock
          git commit -m "temp version bump" || true
          git checkout "$PR_BRANCH"
          git diff --ignore-space-at-eol --ignore-blank-lines _tmp_master -- pyproject.toml uv.lock > /tmp/compare.diff || true
          if [ -s /tmp/compare.diff ]; then
            echo "❌ PR branch does not match a clean version bump from master."
            cat /tmp/compare.diff
            echo "bump_check=false" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "✅ PR branch matches a clean version bump from master."
            echo "bump_check=true" >> $GITHUB_OUTPUT
          fi
          git branch -D _tmp_master
        env:
          PR_NUMBER: ${{ steps.check-pr-type.outputs.pr_number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto-merge PR
        if: steps.check-pr-type.outputs.allowed == 'true' && steps.validate_bump.outputs.bump_check == 'true'
        env:
          PR_NUMBER: ${{ steps.check-pr-type.outputs.pr_number }}
          GH_TOKEN: ${{ secrets.AUTO_RELEASE_TOKEN }}
        run: |
          gh pr merge "$PR_NUMBER" --squash --delete-branch
          echo "✅ Auto-merged PR #$PR_NUMBER"
