name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if not Master branch
        if: github.ref != 'refs/heads/master'
        
        run: |
          echo "Release can only happen from Master branch"
          exit 1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: 3.12.3
          enable-cache: true
          ignore-nothing-to-cache: true

      - name: Get current version
        id: current_version
        run: |
          echo "version=$(uv version --short)" >> $GITHUB_OUTPUT

      - name: Bump version
        run: |
          uv version --bump ${{ github.event.inputs.release_type }}

      - name: Get new version
        id: new_version
        run: |
          echo "version=$(uv version --short)" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit version bump
        run: |
          git add pyproject.toml uv.lock
          git commit -m "Bump version to v${{ steps.new_version.outputs.version }}"

      - name: Push commit and tag
        run: |
          git push origin v${{ steps.new_version.outputs.version }}
