name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: 3.12.3
          enable-cache: true
          ignore-nothing-to-cache: true

      - name: Get current version
        id: current_version
        run: |
          echo "version=$(uv version --short)" >> $GITHUB_OUTPUT

      - name: Bump version
        run: |
          uv version --bump ${{ github.event.inputs.release_type }}

      - name: Get new version
        id: new_version
        run: |
          echo "version=$(uv version --short)" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit version bump
        run: |
          git add pyproject.toml uv.lock
          git commit -m "Bump version to v${{ steps.new_version.outputs.version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.AUTO_RELEASE_TOKEN }}
          branch: release/bump-v${{ steps.new_version.outputs.version }}
          title: "Bump version to v${{ steps.new_version.outputs.version }}"
          commit-message: "Bump version to v${{ steps.new_version.outputs.version }}"
          body: |
            Automated version bump to `v${{ steps.new_version.outputs.version }}`
          base: master
          delete-branch: true
          labels: bump:${{ github.event.inputs.release_type }}
